### Testdata
POST {{base}}/public/testdata

### Authenticate
POST {{base}}/public/inloggen
Content-Type: application/json

{"gebruikersnaam":"m0","wachtwoord":"m0"}

> {%
    client.global.set("token", response.headers.valueOf("Set-Cookie"));
%}
###
GET {{base}}/mijn-groepen
Cookie: {{token}}

###
GET {{base}}/mijn-groepen/182/leerlingen
Cookie: {{token}}

###
GET {{base}}/leerling/891
Cookie: {{token}}

###
GET {{base}}/leerling/300/scores
Cookie: {{token}}

###
GET {{base}}/leerling/300/ouders
Cookie: {{token}}

###
GET {{base}}/leerling/300/groepen
Cookie: {{token}}

###
